Ch front tests 133846507
andela/healthchecks_turquoise pull request #10
Opened 2016-11-28 13:35 UTC by andela-gacheruevans

What does this PR do?

Has the complete tests functions for the pivotal  tracker task  `id 133846507` - `Front tests` and the complete   pivotal tracker task `id 133846617` - `READ ME badges`.

Description of Task to be completed?

Under task `ID 133846507` the following test functions were created;
-Create a function that tests team access works. - ` test_add_check.py` and `test_add_channel.py `
-Create a function that rejects bad kinds. - `test_add_channel.py`
-Create a function that validates priority. - `test_add_pushbover.py`

Under task `ID 133846507` the following Badges were added to the READ ME file created;
-Coverage
-Circle CI
-Code Climate 

Relevant pivotal tracker stories: 
[#133846507] `Front Tests.`
[#133846617] `READ ME Badges.`

2016-11-29 09:06 UTC, uzoawili requested changes

2016-11-29 09:06 UTC, uzoawili commented on hc/front/tests/test_add_channel.py
> +        assert r.status_code == 400, r.status_code
Using Python's `assert` here works just fine. However, Django's `TestCase` (which extends Python's `unittest.TestCase`) class provides wrapper methods (`assertEqual`, `assertContains`, etc.) that are better suited for making assertions within Django tests. Starting with this and going forward let's standardize and make exclusive use of these assert methods e.g `self.assertEquals(..., ...)` as much as possible in our tests. 

Remember that this is mainly for code uniformity (one hallmark of good team collaboration is that our code looks homogeneous - as if it was written by the same person). And yes, Django's wrapper assertion function do offer a few perks we don't get from the Python's `assert`. Although not in this exact scenario.

2016-11-29 09:06 UTC, uzoawili commented on hc/front/tests/test_add_pushbover.py
> +        r = self.client.get("/integrations/add_pushover/?%s" % params)
The objective of this test (I believe) is to ensure that the `prio` parameter is validated and invalid values are not allowed. Where is the assertion for this? `r` is just the response of the GET request. You have to test that response (with assertions) that it actually is what was expected.

2016-11-29 09:06 UTC, uzoawili commented on hc/front/tests/test_add_pushbover.py
>  from django.test.utils import override_settings
This file was incorrectly named originally. This is not from you but fortunately for us, since it's just a small change and you are working on the file at the moment, you can take the opportunity to fix it.

2016-11-29 09:14 UTC, andela-gacheruevans commented on hc/front/tests/test_add_pushbover.py
>  from django.test.utils import override_settings
Thank you on the feedback, was a bit hesitant on changing the wrongly named file at first but now have clarity I shall rename the file to `test_add_pushover.py`

2016-11-29 09:16 UTC, andela-gacheruevans commented on hc/front/tests/test_add_channel.py
> +        assert r.status_code == 400, r.status_code
Thank you for the feedback, will amend my code and work the suggested areas.

2016-11-29 09:28 UTC, andela-gacheruevans commented on hc/front/tests/test_add_pushbover.py
> +        r = self.client.get("/integrations/add_pushover/?%s" % params)
thank you for the feedback, i now have a clear understanding of what I need to test.

2016-12-05 05:04 UTC, uzoawili approved these changes

2016-12-05 05:05 UTC, merged