#133846505 Fix the unit tests on accounts module
andela/healthchecks_turquoise pull request #8
Opened 2016-11-28 09:31 UTC by andela-brotich

#### What does this PR do?
Fix incomplete tests on the `hc/accounts/test` folder
#### Description of Task to be completed?
The folder `hc/accounts` has its unit tests in `hc/accounts/tests`. Some of these tests are incomplete and need fixing and some asserts added.
#### How should this be manually tested?
After cloning the repo and performing the set up according to the ReadMe
- `python manage.py test hc.accounts.tests`
#### Any background context you want to provide?
The files in the `hc/accounts/tests` contain incomplete tests described with lines starting with `##`
#### What are the relevant pivotal tracker stories? #133846505

2016-11-29 12:02 UTC, uzoawili requested changes

2016-11-29 12:02 UTC, uzoawili commented on hc/accounts/tests/test_check_token.py
> +        self.client.login(username="alice@example.org", password="password")
Consider moving the _### Login and test it redirects already logged in_ to a separate test.

2016-11-29 12:02 UTC, andela-uawili commented on hc/accounts/tests/test_login.py
> +        self.assertIn("To log into healthchecks.io, please open the link below:", mail.outbox[0].body)
In testing the content of the email body, consider testing that the right login link is present too and not just the 'copy' string. The copy might be correct but the link in the email might be missing or wrongly formatted. ¯\_(ツ)_/¯

2016-11-29 12:02 UTC, andela-uawili commented on hc/accounts/tests/test_profile.py
>          form = {"invite_team_member": "1", "email": "frank@example.org"}
In the spirit of proper variable naming, `form_data` or simply `data` might be a more apt name to use here, given that forms have a specific meaning in Django

2016-11-29 12:02 UTC, andela-uawili commented on hc/accounts/tests/test_profile.py
> +        form = {'create_api_key': ''}
Refer to previous comment on using `form` as the variable name in this context.

2016-11-29 12:21 UTC, brotich commented on hc/accounts/tests/test_profile.py
> +        form = {'create_api_key': ''}
@andela-uawili noted the changes...will make them and update ASAP

2016-11-30 08:41 UTC, andela-brotich commented on hc/accounts/tests/test_profile.py
>          form = {"invite_team_member": "1", "email": "frank@example.org"}
The variable names have been renamed following the convention: `form` renamed to `form_data` and `r` to `response` on specific files

2016-12-01 06:10 UTC, uzoawili approved these changes

2016-12-01 06:11 UTC, merged